
# initialize the root nispace logger (colored StreamHandler, propagate=False)
from .utils.utils import _init_lgr
_init_lgr("nispace")

# get version and commit (generated by setuptools-scm at install time)
try:
    from ._version import __version__, __commit_id__ as __commit__
except ImportError:
    __version__ = "unknown"
    __commit__ = "unknown"

# hide nilearn deprecation warnings
# TODO: update to nilearn 0.13.0, will require dropping support for python 3.9
import os
import warnings
# Allow opt-in via environment variable
if not os.environ.get("NISPACE_SHOW_FUTURE_WARNINGS"):
    warnings.filterwarnings("ignore", category=FutureWarning, module=r"^neuromaps(\.|$)")
    
# Public API
from .api import NiSpace
from .workflows import (colocalization, group_colocalization, xsea, group_xsea,
                        simple_colocalization, simple_xsea, group_comparison)
from .transforms import mni_to_mni, compute_transform_displacement

