import numpy as np

import logging
lgr = logging.getLogger(__name__)
from ..stats.coloc import pearson, rank2d


_CWR_METHODS = ("pearson", "spearman")


def _validate_cwr_input(X, Y):
    """Validate/cast X, Y for correlate_within_region_core.

    X, Y : array-like, shape (n_subjects, n_parcels) or (n_subjects,)
        At least one of X/Y must be 2D. The 1D case represents a subject-level
        covariate (e.g. age) that gets broadcast against every parcel. A
        (n_subjects, 1) 2D shape is treated identically to the 1D case (squeezed
        down before validation).
    """
    X = np.asarray(X, dtype=np.float64)
    Y = np.asarray(Y, dtype=np.float64)

    if X.ndim not in (1, 2) or Y.ndim not in (1, 2):
        lgr.critical_raise(
            f"X and Y must be 1D or 2D arrays, got ndim={X.ndim}/{Y.ndim}.",
            ValueError
        )
    # a (n_subjects, 1) column is a 1D covariate in disguise -- squeeze it down so it
    # goes through the same broadcast path as a true 1D vector (otherwise the NaN-aware
    # loop path below indexes past column 0 of the "other" side and raises IndexError)
    if X.ndim == 2 and X.shape[1] == 1:
        X = X[:, 0]
    if Y.ndim == 2 and Y.shape[1] == 1:
        Y = Y[:, 0]
    if X.ndim == 1 and Y.ndim == 1:
        lgr.critical_raise(
            "Both X and Y are 1D (subject-level) vectors -- nothing to compute per parcel. "
            "At least one of X/Y must be 2D (n_subjects, n_parcels).",
            ValueError
        )
    if X.shape[0] != Y.shape[0]:
        lgr.critical_raise(
            f"X has {X.shape[0]} subjects, Y has {Y.shape[0]} -- subject counts must match.",
            ValueError
        )
    return X, Y


def _n_parcels(X, Y):
    return X.shape[1] if X.ndim == 2 else Y.shape[1]


def _broadcast_to_2d(arr, n_subjects, n_parcels):
    """1D (n_subjects,) -> materialized (n_subjects, n_parcels) copy; 2D passed through."""
    if arr.ndim == 1:
        return np.array(np.broadcast_to(arr[:, None], (n_subjects, n_parcels)), dtype=np.float64)
    return arr


def _colwise_corr_vectorized(X, Y):
    """Pearson correlation along the subject axis (axis=-2), fully vectorized.

    X, Y : ndarray, broadcastable shapes (..., n_subjects, n_parcels)
        No NaN handling -- callers must pre-filter NaNs (see `_colwise_corr_loop`).
        Works identically for the plain (n_subjects, n_parcels) case and for the
        null-generation case where a leading (n_perm,) axis has been added to one
        side and needs broadcasting against the other.

    Returns
    -------
    rho : ndarray, shape (..., n_parcels)
    """
    Xc = X - X.mean(axis=-2, keepdims=True)
    Yc = Y - Y.mean(axis=-2, keepdims=True)
    num = (Xc * Yc).sum(axis=-2)
    den = np.sqrt((Xc ** 2).sum(axis=-2) * (Yc ** 2).sum(axis=-2))
    with np.errstate(invalid="ignore", divide="ignore"):
        rho = np.where(den > 0, num / den, np.nan)
    return rho


def _colwise_corr_loop(X, Y):
    """NaN-aware fallback: per-parcel Pearson via the njit `pearson()` primitive.

    X, Y : ndarray, shape (n_subjects, n_parcels)
    """
    n_parcels = X.shape[1]
    rho = np.full(n_parcels, np.nan, dtype=np.float64)
    for p in range(n_parcels):
        x, y = X[:, p], Y[:, p]
        mask = ~np.isnan(x) & ~np.isnan(y)
        if mask.sum() < 2:
            continue
        rho[p] = pearson(np.ascontiguousarray(x[mask]), np.ascontiguousarray(y[mask]))
    return rho


def correlate_within_region_core(X, Y, method="pearson", n_perm=1000, seed=None):
    """Per-parcel, across-subject correlation with a subject-label permutation null.

    For each parcel independently, correlates X's subject-level values against Y's
    (across the SUBJECT axis) -- the opposite axis from `colocalize()`, which
    correlates across parcels within a subject/map. The null is generated by
    permuting subject identity (not spin/Moran spatial nulls): the same subject
    shuffle is applied consistently across all parcels within one permutation
    iteration, which is what makes downstream maxT-style FWER correction valid.

    Parameters
    ----------
    X, Y : array-like, shape (n_subjects, n_parcels) or (n_subjects,)
        At least one of X/Y must be 2D. A 1D side is broadcast across every
        parcel (e.g. an external covariate like age).
    method : {"pearson", "spearman"}
    n_perm : int
        Number of subject-label permutations for the null. 0/None skips the
        null entirely (rho only, no p-values).
    seed : int, optional

    Returns
    -------
    rho : ndarray, shape (n_parcels,)
    null : ndarray, shape (n_perm, n_parcels), or None if n_perm is falsy
    """
    if method not in _CWR_METHODS:
        lgr.critical_raise(f"method must be one of {_CWR_METHODS}, got '{method}'.", ValueError)

    X, Y = _validate_cwr_input(X, Y)
    n_subjects = X.shape[0]
    n_parcels = _n_parcels(X, Y)
    X2 = _broadcast_to_2d(X, n_subjects, n_parcels)
    Y2 = _broadcast_to_2d(Y, n_subjects, n_parcels)

    has_nan = np.isnan(X2).any() or np.isnan(Y2).any()

    # ranking is per-column over the subject axis, so it commutes with row
    # (subject) permutation -- safe to rank once, up front, before any shuffles
    if method == "spearman":
        X2 = rank2d(X2)
        Y2 = rank2d(Y2)

    if has_nan:
        rho = _colwise_corr_loop(X2, Y2)
    else:
        rho = _colwise_corr_vectorized(X2, Y2)

    null = None
    if n_perm:
        rng = np.random.default_rng(seed)
        sigma = np.argsort(rng.random((n_subjects, n_perm)), axis=0).T  # (n_perm, n_subjects)
        Y_perm = Y2[sigma]  # (n_perm, n_subjects, n_parcels)
        if has_nan:
            null = np.stack([_colwise_corr_loop(X2, Y_perm[i]) for i in range(n_perm)], axis=0)
        else:
            null = _colwise_corr_vectorized(X2[np.newaxis, :, :], Y_perm)

    return rho, null
